### ISSUE TITLE
Maximize CUDA usage

### ISSUE THREAD

**Issue by ghost** [Alfiuman/WhydahGally-LSTM-MLP#1]
Hello All ! Using the default project I see the CUDA utilization at only 15% using a 1050 Ti (GPU-Z).
Do you know how change the parameters to push this up to fully utilize the GPU ?

**Comment by Alfiuman** [comment]
Hi, if you test the single CUDA algorithms alone they all reach 100% GPU Load easily (using GPU-Z).

Moreover this project wants to be just a basic starting point for CUDA and Neural Networks for Time Series Analysis, hence if you want a fully CUDA machine learning tool you should write the CUDA code also for all the other parallelizable operations and not only for the Linear Algebra ones. In this way you will fully utilize the GPU.

I want also to say that I'm not interest at the moment to share my best CUDA and ANN code but just a basic starting point.

Anyway if you are interested in improving your CUDA skills you should extract the CUDA algorithms, test ad improve them.
I created a testing tool here: https://github.com/Alfiuman/CUDA-Test
I hope it could help.

**Comment by Alfiuman** [comment]
Hi, if you test the single CUDA algorithms alone they all reach 100% GPU Load easily (using GPU-Z).

Moreover this project wants to be just a basic starting point for CUDA and Neural Networks for Time Series Analysis, hence if you want a fully CUDA machine learning tool you should write the CUDA code also for all the other parallelizable operations and not only for the Linear Algebra ones. In this way you will fully utilize the GPU.

I also want to say that at the moment I'm not interested in sharing my best CUDA and ANN code but just a basic starting point.

Anyway if you are interested in improving your CUDA skills you should extract the CUDA algorithms, test and improve them.
I created a testing tool here: https://github.com/Alfiuman/CUDA-Test
I hope it could help.

**Comment by ghost** [comment]
Thanks :)

**Comment by Alfiuman** [comment]
No problem!
