### ISSUE TITLE
computeLoss() does not check for negative arguments

### ISSUE THREAD

**Issue by aboutin33** [Alfiuman/WhydahGally-LSTM-MLP#2]
I recompiled your code for win7 under VS2012. the LSTM algo does not seem to converge with a number of numCell other than 20 with the example you provide.
Playing with the other params like alpha or lossFunct does not seem to help. I have incorporated your latest change in matrix.h, did not fit it. 
Chosing LOSSFUNCTLOGPOW3 or LOSSFUNCTPOW3 create NaN. Can you help ?

The problem is in computeLoss(). The 1st arg1 to lossFunctLogPow3(arg1,arg2) and the others should never be <= 0. because of the log() funciton they call.
The fix is to replace any value <= 0 by a tiny very tiny pos number (+1.0e-20f for example)
This fix eliminates the NaN and the convergence problem for any type of loss function and/or numCell

**Comment by Alfiuman** [comment]
Hi, sorry I didn't see this.
I've fixed this problem and now on my end it converges also with a large numCell. 
Now if it stales for too long please try reducing the alpha.
Please try to recompile on your end.
